### PR TITLE
Mark certificate keys as exportable for compatibility with macOS

### LINKED ISSUE #4056: Broken SSL examples on macOS
For compatibility with macOS we need to set `X509KeyStorageFlags.Exportable`, this was previously done by default with X509Certificate2 constructor, we stop using the constructor because it is deprecated in .NET 9.

```
Unhandled exception. Interop+AppleCrypto+AppleCommonCryptoCryptographicException: MAC verification failed during PKCS12 import (wrong password?)
   at Interop.AppleCrypto.X509ImportCertificate(ReadOnlySpan`1 bytes, X509ContentType contentType, SafeCreateHandle importPassword, SafeKeychainHandle keychain, Boolean exportable, SafeSecIdentityHandle& identityHandle)
   at Interop.AppleCrypto.X509ImportCertificate(ReadOnlySpan`1 bytes, X509ContentType contentType, SafePasswordHandle importPassword, SafeKeychainHandle keychain, Boolean exportable, SafeSecIdentityHandle& identityHandle)
   at System.Security.Cryptography.X509Certificates.AppleCertificatePal.ImportPkcs12NonExportable(AppleCertificatePal cert, SafeSecKeyRefHandle privateKey, SafePasswordHandle password, SafeKeychainHandle keychain)
   at System.Security.Cryptography.X509Certificates.AppleCertificatePal.ImportPkcs12(ReadOnlySpan`1 rawData, SafePasswordHandle password, Boolean exportable, SafeKeychainHandle keychain)
   at System.Security.Cryptography.X509Certificates.AppleCertificatePal.FromBlob(ReadOnlySpan`1 rawData, SafePasswordHandle password, Boolean readingFromFile, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509CertificateLoader.LoadPkcs12(BagState& bagState, ReadOnlySpan`1 password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509CertificateLoader.LoadPkcs12(ReadOnlyMemory`1 data, ReadOnlySpan`1 password, X509KeyStorageFlags keyStorageFlags, Pkcs12LoaderLimits loaderLimits)
   at System.Security.Cryptography.X509Certificates.X509CertificateLoader.LoadFromFile[T](String path, ReadOnlySpan`1 password, X509KeyStorageFlags keyStorageFlags, Pkcs12LoaderLimits loaderLimits, LoadFromFileFunc`1 loader)
   at System.Security.Cryptography.X509Certificates.X509CertificateLoader.LoadPkcs12FromFile(String path, ReadOnlySpan`1 password, X509KeyStorageFlags keyStorageFlags, Pkcs12LoaderLimits loaderLimits)
   at System.Security.Cryptography.X509Certificates.X509CertificateLoader.LoadPkcs12FromFile(String path, String password, X509KeyStorageFlags keyStorageFlags, Pkcs12LoaderLimits loaderLimits)
   at Program.<Main>$(String[] args) in /Users/jose/Documents/icerpc-csharp/examples/slice/Secure/Server/Program.cs:line 10
   at Program.<Main>(String[] args)
```

### PR DESCRIPTION
**Pull request by pepone**
Fix #4056

### CODE REVIEW

**Review by externl — COMMENTED** [review]
What's the difference between `.Exportable` and `.DefaultKeySet`?

**Comment by pepone** [comment]
> What's the difference between .Exportable and .DefaultKeySet?

I think they are unrelated, in macOS without setting the Exportable flag it cannot work because the keys cannot be accessed by common crypt. If I recall correctly the key is read by a separate process in macOS

**Comment by externl** [comment]
> > What's the difference between .Exportable and .DefaultKeySet?
> 
> I think they are unrelated, in macOS without setting the Exportable flag it cannot work because the keys cannot be accessed by common crypt. If I recall correctly the key is read by a separate process in macOS

Why do some servers use one vs the other?

**Comment by pepone** [comment]
> Why do some servers use one vs the other?

An autocompletion typo, should be Exportable everywhere.

**Review by externl — APPROVED** [review]
Do we have a test for this? CI on my PR doesn't seem to be failing with any TLS issues

**Comment by pepone** [comment]
> Do we have a test for this? CI on my PR doesn't seem to be failing with any TLS issues

I noticed this when updating TLS test to work with .NET 9 in issue#3990

**Comment by pepone** [comment]
> Do we need to update the templates as well?

Yes they are still using the deprecated X509Certificate2 constructor.

**Pull request merged**
