### PR TITLE
Fix NuGet Audit build failure

### PR DESCRIPTION
**Pull request by pepone**
This PR fixes the NuGet Audit build failures on main.

### CODE REVIEW

**Comment by bernardnormier** [comment]
I don't understand this fix.

```
rg Microsoft.Extensions.Logging.Console
IceRpc.Retry.Tests/IceRpc.Retry.Tests.csproj
14:    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="8.0.*" />

IceRpc.Tests.Common/IceRpc.Tests.Common.csproj
12:    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="8.0.*" />

IceRpc.Logger.Tests/IceRpc.Logger.Tests.csproj
14:    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="8.0.*" />
bernard@studio tests % 
```

As far I can tell, these two tests (Retry and Logger) need this Logging.Console assembly.

**Comment by pepone** [comment]
> As far I can tell, these two tests (Retry and Logger) need this Logging.Console assembly.

These are pulled by IceRpc.Tests.Common which already has the workaround for JSON

**Review by bernardnormier — APPROVED** [review]
This is just a cleanup PR, to remove extra dependencies?

**Comment by pepone** [comment]
> This is just a cleanup PR, to remove extra dependencies?

No, the build on main started to fail for logger and retry because of NuGet audit

**Pull request merged**
