### PR TITLE
Build QUIC for .net8 and .net9

### PR DESCRIPTION
**Pull request by pepone**
This PR include the following upates:

- Updates QUIC assemblies and tests to target both net8.0 and net9.0
- Harcode TargetFramework for examples, using net8.0 value
- Add RollForward major to IceRpc.ProtocGen
- Remove the `NetRuntimeVersion` property and use `8.0.*` directly
- Add Framework parameter to templates with net8.0|net9.0 choices

### CODE REVIEW

**Review by bernardnormier — APPROVED** [review]
Looks good.

**Comment by pepone** [comment]
> CI is failing however.

There is already an issue for this failure, see #3990

**Comment by externl** [comment]
> > CI is failing however.
> 
> There is already an issue for this failure, see #3990

When I commented the build was failing because of the yml.

**Comment by externl** [comment]
Can we filter out these failing tests for now somehow?

**Comment by pepone** [comment]
> Can we filter out these failing tests for now somehow?

Yes added Ignore attribute with TODO and link to the issue

**Pull request merged**
